### ISSUE TITLE
Stitch Integration error

### ISSUE THREAD

**Issue by Hayleycsck** [singer-io/tap-yotpo#2] opened 2019-01-15 13:38 UTC
Hello all, I am getting what seems to be an Python error in my Yotpo -> Stitch integration. The error is: **'NoneType' object is not subscriptable**.

I'm also including a screen shot of the code for reference. 

At the moment, my integration is not working at all because of this error, so any help would be appreciated :)

<img width="1084" alt="screen shot 2019-01-15 at 13 32 58" src="https://user-images.githubusercontent.com/39490891/51183765-241f4400-18ca-11e9-88f9-1d65c744afa0.png">

**Comment by KAllan357** [comment] 2019-01-16 17:32
@Hayleycsck I think this is indicating a problem in the response you are receiving. Are you able to run this tap yourself and see the error?

**Comment by Hayleycsck** [comment] 2019-01-17 10:49
Hi, I don't currently have the setup to run a tap and identify the error. If it is simple, I may be able to set this up myself, but this isn't really my area :)

**Comment by briamkin** [comment] 2019-02-13 21:53
I get the same error here, @Hayleycsck have you figured out any way around this? My connection doesn't seem to recover from this.

**Comment by briamkin** [comment] 2019-02-16 01:05
I guess the solution is to turn off the product_reviews table! I believe that info is already in the reviews table.

**Comment by TomaszE** [comment] 2019-04-10 12:03
Hi Guys, I am following up after Hayley,  we still do experience the same issue here.. 
I disagree with Briam - it's not the same data - it's all depends how your yotpo account is set up - you can ask customer to review your service, order or specific product - and specific product reviews are in product_review tables - it's not the same data - at least in reviews table - you can't see product ID customer is reviewing .

**Comment by joshtemple** [comment] 2019-05-29 18:06
I'm also experiencing this error and it's preventing sync happening beyond the initial historical load. It looks like the last request returns a 404 which is probably what's causing this error. Maybe we're trying to retrieve something out of the possible date range? Not too familiar with this tap.

Here's my log:
```
2019-05-29 15:52:07,386Z    tap - INFO HTTP request to "product_reviews" endpoint took 0.012s, returned status code 200
2019-05-29 15:52:07,396Z    tap - INFO HTTP request to "product_reviews" endpoint took 0.009s, returned status code 404
2019-05-29 15:52:07,396Z    tap - CRITICAL 'NoneType' object is not subscriptable
```

**Comment by joshtemple** [comment] 2019-06-18 22:30
@KAllan357, I've identified why this tap is breaking.

First of all, it's not handling a 404 response from the API.

See the code [here](https://github.com/singer-io/tap-yotpo/blob/335943368873cccd96be16bcc731fb006e1f41ed/tap_yotpo/http.py#L69) which is returning `None` if a 404 status code found in the response. That `None` gets passed downstream to the `Stream.format_response` method, which tries to treat it like a dictionary and fails.

Secondly, the cause of the 404 is that a long integer `product_id` gets converted to scientific notation (1.52867E+12), breaking the request for Product Reviews. This conversion must happen somehow during the `product_id` caching process between the Products and Product Reviews streams. The [Products stream](https://github.com/singer-io/tap-yotpo/blob/master/tap_yotpo/streams.py#L119) calls `singer.write_records` via the [write_records method](https://github.com/singer-io/tap-yotpo/blob/master/tap_yotpo/streams.py#L42) in the base Stream class. I'm guessing that's where the integer is getting transformed.

Any recommendation for how to fix these issues?

**Comment by KAllan357** [comment] 2019-06-19 20:00
It sounds like the 404 is an unrecoverable error and that ideally we'd want to raise an exception here. If that's not the case, I say we should consider adding a `continue` statement (and some logging) in the `while` loop here - https://github.com/singer-io/tap-yotpo/blob/335943368873cccd96be16bcc731fb006e1f41ed/tap_yotpo/streams.py#L86-L87.

If I understand the second issue correctly, it sounds like the `path` variable is getting formatted badly ie:  `"widget/:api_key/products/{product_id}/reviews.json" ->  "widget/:api_key/products/1.52867E+12/reviews.json"`? The code goes - retrieve records, transform them against the schema, and then maybe store the records in the cache. I don't think I can speculate what's happening here but I'd start with wanting to know what the raw-response from Yotpo looked like. I see that the schema for `"external_product_id"` is string. When the schema says string, it converts the value:

```
>>> str(1528670000000000000000000000000000000000)
'1528670000000000000000000000000000000000'
```

So I'm not entirely sure how this is happening.

**Comment by cbglo** [comment] 2020-01-15 22:32
Was anyone able to find a workaround for this issue?

**Comment by TomaszE** [comment] 2020-02-14 09:44
Hi Guys, this hangs here for a very long time. I do understand this is an community, but i really don't have knowledge how to fix that issue - can someone please help us and fix it ?

**Comment by JDW818** [comment] 2021-01-18 18:06
Currently running into this exact same issue. Curious if anyone on the thread was ever able to find a solution.

**Comment by msmith91** [comment] 2021-07-13 19:59
I've been facing this issue and have traced back the specific 'scientific notation' error to the product catalog in Yotpo.  In my instance, a product had been added to the Yotpo product catalog incorrectly with scientific notation in error.  I think the fix for this specific to yotpo tap should be as @KAllan357 stated - an exception and logging but a `continue` in the while loop so as not to break the sync.  

I've further noticed that these failures are partially loading the product review data to the target.  I'm seeing multiple loads for the same records for each failed extract & load job in stitch (not sure if this is a stitch implementation issue or the yotpo tap implementation... I'm fairly new here :/ )

**Comment by Vi6hal** [comment] 2022-08-17 08:08
This issue will be fixed in the upcoming major release.

https://github.com/singer-io/tap-yotpo/blob/4913f133b6554185812388edf1e1beeeabe1049f/tap_yotpo/streams/product_reviews.py#L116

**Closed** 2023-04-07 14:25 UTC
Labels: help wanted
